### ISSUE TITLE
delete .mount_test_from

### ISSUE THREAD

**Issue by beig** [echocat/nagios-plugin-check_mountpoints#19]
Hello,

where should I insert a delete so it doesn't screw up the script.
I monitor a bunch of windows-shares and the amount of .mount_test_files is huge.

Thank you

**Comment by dwerder** [comment]
This line should already delete the test file:
https://github.com/echocat/nagios-plugin-check_mountpoints/blob/master/check_mountpoints.sh#L297

**Comment by beig** [comment]
Oh snap. I think I know what the problem was.
I added touch to the sudoers but didn't add rm (and no sudo rm)

Thank you
