### ISSUE TITLE
Check not working with ZFS 

### ISSUE THREAD

**Issue by Bbertatum** [echocat/nagios-plugin-check_mountpoints#26]
Hi, 

First, thanks for the code check. I wish that the script work on FreeBSD with ZFS.
The code is actually running on several machines (Linux CentOS (XFS and FreeBSD) without problems.

I've done several changes (bash => sh) and some tweaks to be compliant with zfs (no fstab) and readonly filesystem for zfs send snapshot purpose.

Could you check my changes and tell it's enough clean to integrate it to the main tree of the project ?

I think it could be a good feature added :)

Thanks

Bertrand

[check_mountpointsZFS.sh.zip](https://github.com/echocat/nagios-plugin-check_mountpoints/files/467034/check_mountpointsZFS.sh.zip)

**Comment by Bbertatum** [comment]
I forgot to mention that I also modified the behavior of the script to avoid doin "rm" on the file.
I simply don't add date/time into the name of the file.

I just add the latest commit there : 

[check_mountpointsZFS.sh.zip](https://github.com/echocat/nagios-plugin-check_mountpoints/files/467432/check_mountpointsZFS.sh.zip)

**Comment by dwerder** [comment]
Sorry for the late response. The PR #31  added support for FreeBSD but still not ZFS.
You can take a look at it and mabye open an PR with your changes.
