### ISSUE TITLE
Trailing slash in mountpoint not removed before string comparison

### ISSUE THREAD

**Issue by fredricj** [echocat/nagios-plugin-check_mountpoints#30]
If a mountpoint in fstab contains a trailing slash the check for that mount will fail to find the correctly mounted filesystem since the slash is not included in /proc/mounts

**Comment by dwerder** [comment]
This was fixed by #31

**Comment by MasterofJOKers** [comment]
Doesn't db47b24b9941d11d4c5ae20afb3dab6e0dc6cfea only remove the trailing slash on the last found mountpoint in `/etc/fstab? So if my checked mountpoint isn't the last one in the list, it still wouldn't match.

**Comment by dwerder** [comment]
You are right. The fix should be simply to set the "sed" before the "tr"

**Comment by dwerder** [comment]
Should be fixed in a2dd8db1f4eac2b858476c350f4922370651dd58

**Comment by MasterofJOKers** [comment]
Switching `sed` and `tr` only works, if you never expect anyone to monitor the rootfs mounted in `/`, as the `/` would get removed.

**Comment by dwerder** [comment]
You are right. So the sed command should look like `s/?\/$//i`

**Comment by MasterofJOKers** [comment]
Don't you mean `s/(.)\/$/\1/i` or something like that? Not that good at `sed`, sorry.

**Comment by r-daneel** [comment]
Actually, `s/\(.\+\)\/$/\1/` seems more appropriate.
We want to strip trailing '/' only if there is anything before it (excluding a standalone '/')
