### ISSUE TITLE
pluguin not working with opsview

### ISSUE THREAD

**Issue by marouajaouachi** [echocat/nagios-plugin-check_mountpoints#37]
hello i've integred the nagios plaguin on opsview , testing it locally it's working but the pluguin is not working on my Opsview server.

this is the configuration made : -H $HOSTADDRESS$ -c check_mountpoints  -a '$MOUNTPOINT$' -C '%NRPE_CERTIFICATES:1%' -k '%NRPE_CERTIFICATES:2%' -r '%NRPE_CERTIFICATES:3%' -y '%NRPE_CIPHERS:1%'

the error i get is : 

Status Information | NRPE: Unable to read output
by troubleshooting i got : Caught exception in Opsview: :Web::Controller::REST::TestServiceCheck->do_testservicecheck "Unhandled macros"

Any ideas ? 

Thanks

**Comment by dwerder** [comment]
Stale and closed
