### ISSUE TITLE
Script does not work on Solaris 11 

### ISSUE THREAD

**Issue by stauraum** [echocat/nagios-plugin-check_mountpoints#40]
What is wrong here?! :-O

root@nfsclnt ~ # grep -i nfsserver /etc/vfstab
nfsserver:/mnt - /mnt nfs - yes rw,xattr

root@nfsclnt ~ # grep -i nfsserver /etc/mnttab
nfsserver:/mnt /mnt nfs rw,xattr,dev=9300001 1507803587

root@nfsclnt ~ # ./check_mountpoints.sh /mnt
CRITICAL: /mnt is not mounted ;

**Comment by dwerder** [comment]
Is the mountpoint a symbolic link (softlink) ? Then you need to set parameter -L

**Comment by stauraum** [comment]
No, the mountpoint is a regular directory:

# ls -l / | grep mnt
drwxr-xr-x 4 root sys 4 Feb 3 2017 /mnt

If i create a new directory called /1 and mount the share from the server, the error is the same.

**Comment by dwerder** [comment]
Stale and closed
