### ISSUE TITLE
False return

### ISSUE THREAD

**Issue by wforumw** [echocat/nagios-plugin-check_mountpoints#41]
Hi 

If I check the script via check_nrpe I get a critical back
```
check_nrpe -H server1 -c check_mounts
CRITICAL: /data/dir1 doesn't exist on filesystem
```
but if I run the script locally (@server1) it gives back the correct information
```
/usr/lib/nagios/plugins/check_mountpoints.sh -a
OK: all mounts were found ( /data/dir1 )
```

my nrpe.cfg on the checked server1 is
command[check_mounts]=/usr/lib/nagios/plugins/check_mountpoints.sh -a

/data/dir1 is a NFS mountpoint

Any idea why I get this?
Many thanks!!

**Comment by dwerder** [comment]
Maybe nrpe has no permision to "see" ( read ) the /data/ drectory?
Just a gues,
Did you run the script locally on the server with the same user as nrpe runs?

**Comment by wforumw** [comment]
Thanks, now it works!!

**Comment by Vict0rC** [comment]
Hello, I have same problem...
when runnig locally as nrpe user:

# su nrpe
[nrpe@srv]
/ # /usr/lib64/nagios/plugins/check_mountpoints.sh -a
OK: all mounts were found ( /boot /fbdata /home /tmp /usr /var /mnt/backup )

/mnt/backup is fully accessible for nrpe user, tested and works!

even this work when root:
/ # sudo -u nrpe /usr/lib64/nagios/plugins/check_mountpoints.sh -a
OK: all mounts were found ( /boot /fbdata /home /tmp /usr /var /mnt/backup )

but, when I call with nrpe:
/ # /usr/lib64/nagios/plugins/check_nrpe -H 127.0.0.1 -c check_mntpoints
CRITICAL: /mnt/backup doesn't exist on filesystem ;

nrpe.cfg:
log_facility=daemon
nrpe_user=nrpe
nrpe_group=nrpe
command[check_mntpoints]=sudo /usr/lib64/nagios/plugins/check_mountpoints.sh -a

Any idea?
Thanx for help
VicC
