### ISSUE TITLE
False return #2

### ISSUE THREAD

**Issue by Vict0rC** [echocat/nagios-plugin-check_mountpoints#42]
Hello, I have same problem like here: https://github.com/echocat/nagios-plugin-check_mountpoints/issues/41
when runnig locally as nrpe user:

>su nrpe
>[nrpe@srv]
>/ # /usr/lib64/nagios/plugins/check_mountpoints.sh -a
>OK: all mounts were found ( /boot /fbdata /home /tmp /usr /var /mnt/backup )

/mnt/backup is fully accessible for nrpe user, tested and works!

even this work when root:
>[root@srv]
>/ # sudo -u nrpe /usr/lib64/nagios/plugins/check_mountpoints.sh -a
>OK: all mounts were found ( /boot /fbdata /home /tmp /usr /var /mnt/backup )

but, when I call with nrpe:
>[**root**@srv]
>/ # /usr/lib64/nagios/plugins/check_nrpe -H 127.0.0.1 -c check_mntpoints
>CRITICAL: /mnt/backup doesn't exist on filesystem ;
and
>[**nrpe**@srv]
>/ # /usr/lib64/nagios/plugins/check_nrpe -H 127.0.0.1 -c check_mntpoints
>CRITICAL: /mnt/backup doesn't exist on filesystem ;

ps | grep nrpe
>nrpe     10551  0.0  0.0  41492  1480 ?        Ss   10:47   0:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d

nrpe.cfg:
>log_facility=daemon
>nrpe_user=nrpe
>nrpe_group=nrpe
>command[check_mntpoints]=sudo /usr/lib64/nagios/plugins/check_mountpoints.sh -a

/mnt/backup is nfs mountpoint
ls -la /mnt/
>drwxr-xr-x.  3 root root 4096 Nov 22  2016 .
>drwxr-xr-x. 23 root root 4096 Sep 15 11:04 ..
>drwxr-xr-x. 20 root root 4096 Oct 25 09:40 backup

/etc/fstab
>192.168.101.130:/backup /mnt/backup nfs auto 0 0

Any idea?
Thanx for help
VicC

**Comment by aknotik** [comment]
Hello,

I have exactly the same issue. dwerder, did you solve the issue?

**Comment by dwerder** [comment]
Stale and closed
