### ISSUE TITLE
Doesn't read mountpoints correctly on CentOS 7

### ISSUE THREAD

**Issue by vasiliev123** [echocat/nagios-plugin-check_mountpoints#43]
Hello I've got a problem with autodetection from fstab.

Version 2.0 have found only
/
/backup
/replica

But my actual mountpoints in fstab are:
/ = ext4
/boot = ext2
/backup = ext4
/replica = ext4

so I've tried adding /boot mount manually and it said that /boot is not in /etc/fstab and is not mounted at all
So I've updated to the newest version and result of my command with autodetection is:

/usr/lib64/nagios/plugins/check_mountpoints.sh -a
OK: all mounts were found ( /backup /replica )

But when I manually added / /boot /backup and /replica:

/usr/lib64/nagios/plugins/check_mountpoints.sh / /boot /backup /replica
OK: all mounts were found ( / /boot /backup /replica)

Is there any solution to this? :) I've tried also the -f option with no results

Regards,
vasiliev

**Comment by dwerder** [comment]
Oh, there is someone out there still using ext2 :-D
It is fixed in version 2.4 (37ef5d5662504878e041984c9c048045c70adb38).

**Comment by vasiliev123** [comment]
Yes I have habit to give ext2 for /boot partitions ;)
I still wonder why my root mountpoint doesn't get autoselected

Now after executing I get my ext2 and two others ext4 but no root (/) mountpoint

[root@server ~] /usr/lib64/nagios/plugins/check_mountpoints.sh -a
OK: all mounts were found ( /boot /backup /replica )

But when I use:
[root@server ~]# /usr/lib64/nagios/plugins/check_mountpoints.sh / /boot /backup /replica
OK: all mounts were found ( / /boot /backup /replica)

The root partition is there :)

Maybe it has something to do with /proc/mounts file?
